# This is a basic workflow to help you get started with Actions

name: 'Update Bot'
 
on:
  workflow_dispatch:
  schedule:
    - cron: '10 10 */2 * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Ubuntu'
        uses: actions/checkout@v1
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: 'Install dependencies'
        run: pip install requests
      - name: 'update'
        run: python3 ./update.py
      - name: 'commit'
        run: |
          git config --global user.email 172283627+eslion@users.noreply.github.com
          git config --global user.name eslion
          git add *
          git commit -m "Update by Eslion Bot"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
